# permissions for end users to edit nifireplicaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifireplicacluster-editor-role
rules:
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifireplicaclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.konpyutaika.com
  resources:
  - nifireplicaclusters/status
  verbs:
  - get
